### Carga de Imagen a Cloudinary
# URL: http://localhost:8080/api/images
# Método: POST
# Tipo de Contenido: multipart/form-data

POST http://localhost:8080/api/images
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJyb2xlIjoiUk9MRV9IT1NUIiwibmFtZSI6IkFkbWluIiwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJzdWIiOiI4YWYyYzBmZi0yZmUxLTQ1ZDgtOTRkYS03M2UzMjUxOTRhMTIiLCJpYXQiOjE3NTk1NDU5MzYsImV4cCI6MTc1OTU0OTUzNn0.tuxLAxz6PjkBqK2_l6ekFv1e4ghL4tetT0z5p6tOH9dKmln2O9JH0iiF-KCqBmDg



--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Kaladin_Lyon.png.5c0b30937c260bf7f14bde7c50a5f8b0.png"
Content-Type: image/png

< /Users/lala/Downloads/Kaladin_Lyon.png.5c0b30937c260bf7f14bde7c50a5f8b0.png

--WebAppBoundary--
