POST http://localhost:8080/api/auth/register
Content-Type: application/json

{
  "name" : "Willy",
  "phone" : "123123123",
  "email" : "willy@gmail.com",
  "password" : "willy123",
  "dateBirth": "2000-05-20",
  "role": "GUEST"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email" : "ramirezcarmonajuandavid123@gmail.com",
  "password" : "juandavid_14"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "email" : "willy@gmail.com",
  "password" : "willy123"
}
###
@token = {{response.body.token}}

###

POST http://localhost:9090/api/auth/register
Content-Type: application/json

{
  "name" : "Admin",
  "phone" : "123123123",
  "email" : "admin@gmail.com",
  "password" : "123juan",
  "dateBirth": "2000-05-20",
  "role": "HOST"
}

###

POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
  "email" : "admin@gmail.com",
  "password" : "123juan"
}

###

POST http://localhost:9090/api/accommodations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsIm5hbWUiOiJBZG1pbiIsInJvbGUiOiJST0xFX0hPU1QiLCJzdWIiOiIyYzMwNGI1OC0xOTE0LTRhODctYmIzMS00YTY4OTE5MDg0YmMiLCJpYXQiOjE3NTk2MzU3OTksImV4cCI6MTc1OTYzOTM5OX0.eQ5Y6k3QVc--f-jNu_ySpXA67wNlAgqq2ZBaCczhiqKMQZqvo1WZR6KSJJcJimrG

{
  "title": "Casa ",
  "description": "lorem asdksadlasd aslkdklasdkl",
  "city": "Bogota",
  "address": "Calle 123 #45-67",
  "latitude": 4.60971,
  "longitude": -74.08175,
  "pricePerNight": 150000,
  "maxGuests": 4,
  "services": ["WIFI"],
  "images": ["img1.jpg", "img2.jpg"],
  "mainImage": "img1.jpg",
  "minImage": 1,
  "maxImages": 5
}

###

POST http://localhost:9090/reservations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJuYW1lIjoidGVzdGVyIiwiZW1haWwiOiJyYW1pcmVzanVhbmRhMTIzQGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0dVRVNUIiwic3ViIjoiOWM5MjE2MDUtNmZhNC00MTlmLTllMGUtZTdjNTRlNmY5M2Q0IiwiaWF0IjoxNzYwMTMzMTUzLCJleHAiOjE3NjAxMzY3NTN9.PrXRQEzTcPaEPCdc2znyzn3yHa6wnQ1S-HJ8tz2BpYoRO9ellLfnZSKiJNnLCeOy

{
  "accommodationId": 2,
  "checkIn": "2025-10-11T14:00:00",
  "checkOut": "2025-11-16T12:00:00",
  "guests": 2
}

###

POST http://localhost:9090/api/auth/register
Content-Type: application/json

{
  "name" : "tester",
  "phone" : "123123123",
  "email" : "ramiresjuanda123@gmail.com",
  "password" : "12345678",
  "dateBirth": "2000-05-20",
  "role": "GUEST"
}

###

POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
  "email" : "ramiresjuanda123@gmail.com",
  "password" : "12345678"
}

### Obtener todos los alojamientos

GET http://localhost:9090/api/accommodations?services=wifi

Accept: application/json

###