### Variables
# Token JWT del usuario 'tester' (ya logueado)
@token = eyJhbGciOiJIUzM4NCJ9.eyJlbWFpbCI6IndpbGx5QGdtYWlsLmNvbSIsIm5hbWUiOiJXaWxseSIsInJvbGUiOiJST0xFX0dVRVNUIiwic3ViIjoiMTQ0YjhkN2UtYzQyMi00N2VkLTk0ZTEtZGNlYWI5ODhiZGVhIiwiaWF0IjoxNzYwMjM1ODY2LCJleHAiOjE3NjAyMzk0NjZ9.XaHc_35EsEL8FS_HA9z7ZsPK1xICKEpcetPrn-boPi5FiTWgVipgcyP7-C1t0bvi
@baseUrl = http://localhost:9090/api/images

---
### P1: Carga de Imagen PNG (Test con Content-Type: image/png)
# Debe funcionar tras la corrección en ImageServiceImpl.convert()
POST {{baseUrl}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="snoopy.jpg"
Content-Type: image/jpg

< /Users/lala/Downloads/snoopy.jpg

--WebAppBoundary--

---
### P2: Carga de Imagen JPEG (Test con Content-Type: image/jpeg)
# Usando el Content-Type correcto para archivos JPG
POST {{baseUrl}}
Content-Type: multipart/form-data; boundary=WebAppBoundary2
Authorization: Bearer {{token}}

--WebAppBoundary2
Content-Disposition: form-data; name="file"; filename="snoopy.jpg"
Content-Type: image/jpg

< /Users/lala/Downloads/snoopy.jpg

--WebAppBoundary2--
### P2: Eliminar Imagen de Cloudinary (DELETE /api/images)
# Usa el ID que obtuviste en la respuesta de P1.
DELETE http://localhost:9090/api/images?id=stayNow/ep2n24kcekwo9aoblbdd
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJlbWFpbCI6IndpbGx5QGdtYWlsLmNvbSIsIm5hbWUiOiJXaWxseSIsInJvbGUiOiJST0xFX0dVRVNUIiwic3ViIjoiMTQ0YjhkN2UtYzQyMi00N2VkLTk0ZTEtZGNlYWI5ODhiZGVhIiwiaWF0IjoxNzYwMjM1ODY2LCJleHAiOjE3NjAyMzk0NjZ9.XaHc_35EsEL8FS_HA9z7ZsPK1xICKEpcetPrn-boPi5FiTWgVipgcyP7-C1t0bvi