### Variables
# Token JWT del usuario 'tester' (ya logueado)
@token = eyJhbGciOiJIUzM4NCJ9.eyJuYW1lIjoiV2lsbHkiLCJlbWFpbCI6IndpbGx5QGdtYWlsLmNvbSIsInJvbGUiOiJST0xFX0dVRVNUIiwic3ViIjoiMDkzYWQwMzEtOGRmNC00YTdjLWI5MGEtZWM1MmMwYjNkNDY5IiwiaWF0IjoxNzYwMjA5NzYwLCJleHAiOjE3NjAyMTMzNjB9.J7EDbRml0h_NE_IyUo_H0cE-ai9i80_P7SJPey87V7miB5plQf7tZw-IyaYjSeap
@baseUrl = http://localhost:9090/api/images

---
### P1: Carga de Imagen PNG (Test con Content-Type: image/png)
# Debe funcionar tras la corrección en ImageServiceImpl.convert()
POST {{baseUrl}}
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer {{token}}

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Kaladin_Lyon.png"
Content-Type: image/png

< C:\\Users\\ramir\\Downloads\\gato.jpg

--WebAppBoundary--

---
### P2: Carga de Imagen JPEG (Test con Content-Type: image/jpeg)
# Usando el Content-Type correcto para archivos JPG
POST {{baseUrl}}
Content-Type: multipart/form-data; boundary=WebAppBoundary2
Authorization: Bearer {{token}}

--WebAppBoundary2
Content-Disposition: form-data; name="file"; filename="xd.jpg"
Content-Type: image/jpeg ⬅️ Nota: Se recomienda 'image/jpeg' o 'image/jpg'

< /Users/lala/Downloads/xd.jpg

--WebAppBoundary2--